### ISSUE TITLE
How to use strategy for publish messages that could not be handled

### ISSUE THREAD

**Issue by matiux** [SimpleBus/AsynchronousBundle#19]
Hi, in a command handler I'd like to fire an event that, in the absence of an event handler, it should be published in a Sqs Amazon queue. This is my command handler:

```
class WriteNewPostCommandHandler
{
    private $postRepository;
    private $eventBus;

    public function __construct(PostRepository $postRepository, AsynchronousEventBus $eventBus)
    {
        $this->postRepository = $postRepository;
        $this->eventBus = $eventBus;
    }

    public function handle(WriteNewPost $command)
    {
        $post = new Post(
            $this->postRepository->nextIdentity(),
            $command->postTitle(),
            $command->postBody()
        );

        $this->postRepository->add($post);

        $event = new PostWasWritten($post->id());

        $this->eventBus->handle($event);
    }
}
```

this is my service definition:
```
    write_new_post_command_handler:
        class: Acme\CoolBlog\Application\Command\Post\WriteNewPostCommandHandler
        tags:
            - { name: command_handler, handles: Acme\CoolBlog\Application\Command\Post\WriteNewPost }
        arguments: ['@post_repository', '@asynchronous_event_bus']
```

I don't know if the `'@asynchronous_event_bus'` is the right dependency.

If I'm not mistaken, I need to append an instance of `PublishesUnhandledMessages` middleware in the event bus. How can I do this in symfony?
