### ISSUE TITLE
Use custom Envelope

### ISSUE THREAD

**Issue by manelselles** [SimpleBus/AsynchronousBundle#5]
Any way to use a custom Envelope object? There is no way to define a custom envelope factory at service simple_bus.asynchronous.standard_message_in_envelop_serializer

You can define a serializer but this serializer is called twice: first for the event and then for the envelope.

Why to force the payload field of message to have the structure of message_type and serialized_message? How to define a different message_type? I want it to be an attribute of the event, not the classname of the event. How to change the structure of this message?

**Comment by prgTW** [comment]
just override `simple_bus.asynchronous.message_serializer` alias to whatever You want like
```yaml
simple_bus.asynchronous.message_serializer:
        alias: my_custom_serializer

my_custom_serializer:
        class: 'MyCustomerSerializer'
        public: false
        arguments:
            - '@simple_bus.asynchronous.object_serializer'
```

```php
<?php

class MyCustomerSerializer implements MessageInEnvelopSerializer
{
	/** @var \SimpleBus\Serialization\ObjectSerializer */
	protected $objectSerializer;

	public function __construct(\SimpleBus\Serialization\ObjectSerializer $objectSerializer)
	{
		$this->objectSerializer = $objectSerializer;
	}

	/** {@inheritdoc} */
	public function wrapAndSerialize($message)
	{
		// Implement
	}

	/** {@inheritdoc} */
	public function unwrapAndDeserialize($serializedEnvelope)
	{
		// Implement
	}
}
```
